### ISSUE TITLE
`Tooltip` does not open on mobile phones

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#1138]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.1

### Description

When I tap on the tooltip, I expect it to show, but it does not.

### Link to Reproduction

https://yamada-ui.com/components/overlay/tooltip

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by quangnmwork** [comment]
Just confirmed the bug. 

And I think here is the reason.

So first on `Tooltip.tsx`  on `getTriggerProps` func we have some line code : 

`
   onPointerEnter: handlerAll(props.onPointerEnter, (e) =>
          e.pointerType !== "touch" ? openWithDelay() : undefined,
   ),
` 

The reason why tooltip not trigger on mobile is because `pointerType` will be `touch' . So that's why tooltip will never be triggered on mobile device.

So I suggest change like this : 

` onPointerEnter: handlerAll(props.onPointerEnter, openWithDelay),`

And then : 

```
 useEventListener(() => triggerRef.current, "pointerleave", (e) => {
      if(e.pointerType !== 'touch')  closeWithDelay();
    })
```

This will make sure when you touch on tooltip trigger element and when leave the element on mobile. It's still displayed.


And finally , to trigger close when click outside we should event handler click outside for this Tooltip component.

That's my idea . 

If you think that's a good idea . Tell me. I think I can fix it .

Ref : https://ant.design/components/tooltip/

**Comment by taroj1205** [comment]
Hi @quangnmwork, thank you for your comment.
Yes, that sounds good :)
I will assign it to you. Good luck!
