### ISSUE TITLE
Research meter accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1503]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/meter/) and research meter accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by illionillion** [comment]
- Keyboard Interaction
  - Not applicable.
- WAI-ARIA Roles, States, and Properties
  - [ ] The element serving as the meter has a role of [meter](https://w3c.github.io/aria/#meter).
  - [ ] The meter has [aria-valuenow](https://w3c.github.io/aria/#aria-valuenow) set to a decimal value between aria-valuemin and aria-valuemax representing the current value of the meter.
  - [ ] The meter has [aria-valuemin](https://w3c.github.io/aria/#aria-valuemin) set to a decimal value less than aria-valuemax.
  - [ ] The meter has [aria-valuemax](https://w3c.github.io/aria/#aria-valuemax) set to a decimal value greater than aria-valuemin.
  - [ ] Assistive technologies often present aria-valuenow as a percentage. If conveying the value of the meter only in terms of a percentage would not be user friendly, the [aria-valuetext](https://w3c.github.io/aria/#aria-valuetext) property is set to a string that makes the meter value understandable. For example, a battery meter value might be conveyed as aria-valuetext="50% (6 hours) remaining".
  - [ ] If the meter has a visible label, it is referenced by [aria-labelledby](https://w3c.github.io/aria/#aria-labelledby) on the element with role meter. Otherwise, the element with role meter has a label provided by [aria-label](https://w3c.github.io/aria/#aria-label).

**Comment by nakayan5** [comment]
rangeslider is applicable in @yamada-ui/slider

**Comment by nakayan5** [comment]
@setodeve 
please double check

**Comment by nakayan5** [comment]
On second thought.
Rangeslider will now be fixed, so this issue is not necessary.
so there are not component in yamada-ui
