### ISSUE TITLE
Research slider accessibility

### ISSUE THREAD

**Issue by nakayan5** [yamada-ui/yamada-ui#1505]
### Description

read [this article](https://www.w3.org/WAI/ARIA/apg/patterns/slider/) and research slider accessibility

modify component if necessary

### Problem Statement/Justification

none

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

**Comment by illionillion** [comment]
- Keyboard Interaction
  - [ ] `Right Arrow`: Increase the value of the slider by one step.
  - [ ] `Up Arrow`: Increase the value of the slider by one step.
  - [ ] `Left Arrow`: Decrease the value of the slider by one step.
  - [ ] `Down Arrow`: Decrease the value of the slider by one step.
  - [ ] `Home`: Set the slider to the first allowed value in its range.
  - [ ] `End`: Set the slider to the last allowed value in its range.
  - [ ] `Page Up` (Optional): Increase the slider value by an amount larger than the step change made by `Up Arrow`.
  - [ ] `Page Down` (Optional): Decrease the slider value by an amount larger than the step change made by `Down Arrow`.
- WAI-ARIA Roles, States, and Properties
  - [ ] The element serving as the focusable slider control has role [slider](https://w3c.github.io/aria/#slider).
  - [ ] The slider element has the [aria-valuenow](https://w3c.github.io/aria/#aria-valuenow) property set to a decimal value representing the current value of the slider.
  - [ ] The slider element has the [aria-valuemin](https://w3c.github.io/aria/#aria-valuemin) property set to a decimal value representing the minimum allowed value of the slider.
  - [ ] The slider element has the [aria-valuemax](https://w3c.github.io/aria/#aria-valuemax) property set to a decimal value representing the maximum allowed value of the slider.
  - [ ] If the value of aria-valuenow is not user-friendly, e.g., the day of the week is represented by a number, the [aria-valuetext](https://w3c.github.io/aria/#aria-valuetext) property is set to a string that makes the slider value understandable, e.g., "Monday".
  - [ ] If the slider has a visible label, it is referenced by [aria-labelledby](https://w3c.github.io/aria/#aria-labelledby) on the slider element. Otherwise, the slider element has a label provided by [aria-label](https://w3c.github.io/aria/#aria-label).
  - [ ] If the slider is vertically oriented, it has [aria-orientation](https://w3c.github.io/aria/#aria-orientation) set to vertical. The default value of aria-orientation for a slider is horizontal.

**Comment by nakayan5** [comment]
created issue
https://github.com/yamada-ui/yamada-ui/issues/1727
