### ISSUE TITLE
ブラウザがリサイズした時にcarouselの表示がおかしくなる

### ISSUE THREAD

**Issue by hinataOhyama** [yamada-ui/yamada-ui#2421]
### どのパッケージに問題がありますか？

@yamada-ui/carousel

### パッケージのバージョン

2.0.1

### 概要

ブラウザをリサイズすると、
- アクティブスライドが真ん中に来ない。
- 端っこにあるスライドが消滅する。

### 再現手順

1. 'carouselコンポーネントを使用します
2. リサイズします。

### ブラウザ

None

### OS

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### まさか、問題の修正方法をご存知ですか？

None

### この問題の修正に参加し、修正を含むプルリクエストを作成しますか？

None

**Comment by hinataOhyama** [comment]
After examining the issue, there is nothing in particular that we can do ourselves, so I think we can close this issue.
There are two reasons.

One is that when the carousel slides, the translate3d property is only calculated on reload,
This causes a bug when sliding after resizing. This is a problem on the embla-carousel side.
Second, this is a bug that occurs only when resizing, so there is no harm to the user. I think developers may be confused.

**Comment by bmthd** [comment]
I am experiencing a similar issue as here.
When placing a carousel in a dialog, the layout is misaligned from the start, possibly due to the resizing that occurs when the dialog is opened.
This does not occur with shadcn/ui, which uses embla carousel, so it seems like something that needs to be fixed. What do you think?

**Comment by hirotomoyamada** [comment]
@bmthd @hinataOhyama 

Hi, thanks for the comment.

I feel like this is a problem on the Yamada UI side.

**Comment by hinataOhyama** [comment]
@bmthd @hirotomoyamada 
Thank you for your feedback.
Let me proceed with the survey.
