### ISSUE TITLE
Image link is broken

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-ui#3148]
### Provide the exact quote of the error or issue

Image link of `InfiniteScrollArea` component is broken.
It is must be replace.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/data-display/infinite-scroll-area#change-the-orientation

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

**Comment by 5AIPAVAN** [comment]
@108yen can you help me in solving this( i am a beginner) 
-> what i understood is the images in change the orientation horizontal slider is broken
because the image link 'https://gurren-lagann15th.com/assets/img/top/visual.jpg' is not working

what must be the new image link (or where can i find the new link), with which i need to replace this image link to resolve this issue.

**Comment by 108yen** [comment]
@5AIPAVAN 
That's right.

**Comment by 108yen** [comment]
@5AIPAVAN 
I dont know.
Please find a nice image of Gurren Lagann.

**Comment by 5AIPAVAN** [comment]
anyone please assign me this issue @108yen @hifumi9 @seoky0 :-)

**Comment by 5AIPAVAN** [comment]
i have opened a pr that closes this issue, please tell me if you want to change anything :-)
